### PR TITLE
Rearrange proto files

### PR DESCRIPTION
**Pull request by michaelklishin**
Rearrange GPB .proto files

To closer reflect the services provided by etcd.

We lump health checks, cluster membership, alarms into
"maintenance" as they are of less interest to the
users of this client (compared to the K/V, leases, auth
and locking services).

This also introduces a lock.proto to lay a foundation
for the future work on #14.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@zhongwencool I understand that such changes may seem irrelevant and a matter of taste but as a new contributor looking to add support for new services, the previous GPB layout definitely did not help. I'd argue that we should either put together everything into a single .proto file or use a fine-grained structure proposed in this PR.

This also demonstrates the struggle I have with `eetcd_lock_gen.erl` generation mentioned in a comment in #14.

**Comment by michaelklishin** [comment]
What also did not make much sense to me is why we use different packages in all the `proto` files. I figured instead of imports and fully-qualified names we can simply put everything into a single package, `eetcd`. Any reason not to do this given that our file structure is not identical to that of, say, etcd itself?

**Comment by zhongwencool** [comment]
Why I put all the proto in one file?
We use record before `v0.3.0`, the gpb will generate a lot of records in hrl, 
I just put all together roughly. It will make rebar3_eetcd_plugin` more simply.

Since we use maps in `v0.3.0`, rearrange proto make more reasonable.
 But I also make a lot of hard-coded in `rebar3_eetcd_plugin`....
It would be painful to rewrite this code and take a lot of time.

**Comment by michaelklishin** [comment]
But I haven't observed any functional differences. `rebar3_eetcd_plugin` seems to handle these files. How should a new file such as `lock.proto` be added if `rebar3_eetcd_plugin` has hardcoded bits? What are those bits?

**Pull request closed without merging**
