### PR TITLE
[WIP] Introduce eetcd_election

### PR DESCRIPTION
**Pull request by zhongwencool**

### CODE REVIEW

**Comment by zhongwencool** [comment]
We got a gun_trailers msg when campaign timeout.

```erlang
test() ->
    application:ensure_all_started(eetcd),
    logger:set_primary_config(level, info),
    Registers = ["127.0.0.1:2379", "127.0.0.1:2579", "127.0.0.1:2479"],
    Name = test,
    {ok, _Pid} = eetcd:open(Name, Registers),
    {ok, #{'ID' := LeaseID1}} = eetcd_lease:grant(Name, 8),
    {ok, _} = eetcd_lease:keep_alive(Name, LeaseID1),
    {ok, #{'ID' := LeaseID2}} = eetcd_lease:grant(Name, 8),
    {ok, _} = eetcd_lease:keep_alive(Name, LeaseID2),
    LeaderKey = "zw",
    {ok, #{leader := Leader}} = eetcd_election:campaign(Name, LeaderKey, LeaseID1, <<"Leader-V1">>),
    {error, timeout} = eetcd_election:campaign(Name, LeaderKey, LeaseID2, <<"Leader-V2">>),
    {ok, _} = resign(Name, Leader),
    receive {gun_response, _, _, nofin, 200, _} ->
        receive {gun_data, _, _, nofin, Bin} ->
           receive {gun_trailers, _, _, _}  ->
               eetcd_grpc:decode(identity, Bin, 'Etcd.LeaderResponse')
           end
        end
    end.
```
Result:
```
{ok,#{header =>
          #{cluster_id => 11360555963653019356,
            member_id => 13803658152347727308,raft_term => 3,
            revision => 1876},
      kv =>
          #{create_revision => 0,key => <<"zw">>,lease => 0,
            mod_revision => 1876,value => <<>>,
            version => 8488283890768293795}},
    <<>>}
```

So I introduce campaign_request/response to campaign async.

**Comment by zhongwencool** [comment]
See `test/eetcd_election_leader_example.erl` for more detail.

**Comment by zhongwencool** [comment]
@michaelklishin the lock API also has this block timeout (gun_trailers) situation.
Maybe We should add lock_request/response to handle this?

**Comment by michaelklishin** [comment]
@zhongwencool I have seen them with very low timeouts (e.g. when you mix up seconds and milliseconds), so sure, I think it should be addressed.

**Comment by michaelklishin** [comment]
I like the way this PR is shaping up 👍

**Comment by zhongwencool** [comment]
closes https://github.com/zhongwencool/eetcd/issues/27

**Pull request merged**
