### PR TITLE
Add multiplexing support for watch API

### PR DESCRIPTION
**Pull request by belltoy**
From [etcdv3 API](https://etcd.io/docs/v3.5/learning/api/#watch-streams):

>  A single watch stream can multiplex many distinct watches by tagging events with per-watch identifiers. This multiplexing helps reducing the memory footprint and connection overhead on the core etcd cluster.

However, this PR introduced **breaking changes** to the return type `eetcd_watch:watch_conn/0` and the `eetcd_watch:unwatch/2` function.

In the meantime, these changes may be lack something. For example, if anything error while `watch_stream/2`, the watcher process should perform a new watch request w/ the revisions saved in the `watch_conn/0`, but the revisions (or other metadata of the watch id) of the watch key was missed. That means the watcher process should keep the mapping for the watch key to watch id.

Or maybe we need some more ergonomic API for watching.

### CODE REVIEW

**Comment by belltoy** [comment]
Any ideas? @zhongwencool

**Comment by belltoy** [comment]
Add an example to use multiplexing stream watch.

```erl
rebar3 as test shell
1> application:ensure_all_started(eetcd).
{ok,[cowlib,gun,eetcd]}
2> eetcd_watch_example:start_link().
{ok,<0.473.0>}
```

In another terminal, change keys, change events and inner states will printed on the above console:
```sh
etcdctl put "heartbeat:|T1|127.0.0.1|8888" foo
etcdctl put "heartbeat:|T2|127.0.0.1|8889" bar
etcdctl put "heartbeat2:|T3|127.0.0.1|9988" foo2
etcdctl del "heartbeat:|T2|127.0.0.1|8889"
```

```erl
6> eetcd:info().
| Name           | Status |   IP:Port    | Conn     | Gun      |LeaseNum|
| watch_example_c| Active |127.0.0.1:2379|<0.474.0> |<0.475.0> |      0 |
| Name           | Status |   IP:Port    | Conn     | ReconnectSecond   |
ok

```

**Comment by zhongwencool** [comment]
This PR change is a bit much, I'll look at it when I have time. :)
By the way, can you add test cases in eetcd_watch_SUITE.erl?

**Comment by belltoy** [comment]
Yes, I forgot the test suites, and also the unwatch implementation. Patches were committed and are ready for review.

**Comment by zhongwencool** [comment]
@belltoy 💯

**Pull request merged**
