### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by michaelklishin** [comment]
@zhongwencool if you'd like help with small changes like this, I volunteer to be a contributor to this repo

**Comment by zhongwencool** [comment]
> @zhongwencool if you'd like help with small changes like this, I volunteer to be a contributor to this repo

Much appreciated, I would very much like to invite you to manage this repo together, if you want.

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

@zhongwencool @michaelklishin Moving to [`rebar3_ex_doc`](https://github.com/starbelly/rebar3_ex_doc) soon?

**Comment by michaelklishin** [comment]
@kianmeng it looks nice. You are welcome to contribute the necessary changes :P

**Pull request merged**
